name: Client

on:
  push:
    branches:
      - main
      - developer
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install project dependencies
        run: npm install  # or yarn install if you use Yarn

      # - name: Run tests
      #   run: npm run test

      - name: Build project
        run: npm run build  # Replace 'build' with your actual build script command

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Determine Firebase Hosting Channel and Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          # Determine the Firebase Hosting Channel based on the branch name
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            CHANNEL="client"
          elif [ "${{ github.ref }}" = "refs/heads/developer" ]; then
            CHANNEL="developer"
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            CHANNEL="staging"
          else
            # If the branch is not master, developer, or staging, exit without deploying
            echo "Branch not set up for deployment."
            exit 0
          fi

          # Deploy your application to the specified Hosting Channel
          npm install -g firebase-tools
          firebase hosting:channel:deploy "$CHANNEL" --token "$FIREBASE_TOKEN"

      - name: Deployment status
        run: echo "deployment done"
